import type { Metadata } from "next";
import Navbar from "@/components/Nav";
import Image from "next/image";
import "./globals.css";

export const metadata: Metadata = {
  title: "next-milestone-2-tailwind-css",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Navbar />
        {children}
        <Image
    src="/images.jpg"
    alt="image"
    layout="fill"
    objectFit="cover"
    quality={100}
    style={{ zIndex: -1 }}/>
      </body>
    </html>
  );
}
